- hosts: all
  vars:
    config: "{{ playbook_dir }}/oneview_config.json"
  vars_files:
    - "{{ playbook_dir }}/vars/vars.yml"
  tasks:
    - name: Create Server Profile without specifying a template
      oneview_server_profile:
        config: "{{ config }}"
        data:
          name: "{{ server_name_1 }}"
          serverHardwareTypeName: "{{ server_hardware_type_1 }}"
          serverHardwareName: "{{ server_hardware_mf1_bay3 }}"
          enclosureGroupName: "{{ enclosure_group_name }}"
      delegate_to: localhost

    - name: Power on the server hardware
      oneview_server_hardware:
        config: "{{ config }}"
        state: power_state_set
        data:
          name: "{{ server_hardware_mf1_bay3 }}"
          powerStateData:
            powerState: "On"
            powerControl: "MomentaryPress"
      delegate_to: localhost